service: linkedin-agent-backend

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs20.x
  stage: ${opt:stage, 'dev'}
  region: us-east-1
  memorySize: 512
  timeout: 30
  environment:
    STAGE: ${self:provider.stage}
    JWT_SECRET: ${env:JWT_SECRET}
  httpApi:
    cors:
      allowedOrigins:
        - http://localhost:3000
        - https://*.vercel.app
      allowedHeaders:
        - Content-Type
        - Authorization
      allowedMethods:
        - GET
        - POST
        - PUT
        - DELETE
        - OPTIONS

plugins:
  - serverless-plugin-typescript
  - serverless-offline

functions:
  # Health check endpoint
  health:
    handler: src/handlers/health.handler
    events:
      - httpApi:
          path: /health
          method: get



custom:
  serverless-offline:
    httpPort: 3001
    host: 0.0.0.0 